import React from 'react';

export default function Collaborative() {
  return (
    <section className="max-w-4xl mx-auto px-4 py-10 text-white">
      <h1 className="text-3xl font-bold mb-6">Collaborative Discussion 1 – Summary Post</h1>
      <p className="text-sm italic mb-6"> Friday, 16 May 2025, 5:38 AM</p>

      <div className="space-y-4 text-base leading-relaxed">
        <p>
          The term <strong>big data</strong> refers to the vast volume of digital data generated by multiple sources,
          including software, traditional information transfer and sensors. (Sardar and Panday, 2024)
        </p>

        <p>
          Big data is often unreliable data, and unreliable data must be “cleaned”. Data cleaning is the process of
          quality and sense checking data. (Huxley et al., 2020)
        </p>

        <p>Data can be unreliable because of:</p>
        <ul className="list-disc list-inside ml-4">
          <li>errors by the device or person the data came from, or errors in recording</li>
          <li>extreme or impossible values</li>
          <li>missing values</li>
        </ul>

        <p>
          Before researchers make decisions about cleaning data (such as correcting, transforming, or discarding),
          they need to have a good understanding of what the data represents and how it was collected.
        </p>

        <p>
          Researchers should document the cleaning process so any future audience or researchers are aware of decisions
          that were made. This is often not done. (Huxley et al., 2020)
        </p>

        <p>
          Researchers can use Python tools to clean and analyse data. Python has well developed and tested tools for
          data analysis. <strong>Pandas</strong> is a Python library for data manipulation and analysis. Pandas includes
          reliable tools for reading and writing data in many formats, finding and dealing with missing data, and
          transforming data (McKinney, 2022).
        </p>

        <p>
          If wrong decisions are made during the cleaning process, the analysis of the data can be wrong. Techniques of
          analysis make assumptions about the data; if the data are unreliable, the assumptions might not be correct.
          Analysis of unreliable data will also be unreliable, therefore conclusions will be unreliable.
        </p>

        <h2 className="text-xl font-semibold mt-8">References</h2>
        <ul className="list-disc list-inside ml-4">
          <li>Huxley et al. (2020) <em>Data Cleaning</em>. Sage Foundation.</li>
          <li>McKinney, W. (2022) <em>Python for Data Analysis</em>. O’Reilly Media.</li>
          <li>Sardar & Panday (2024)</li>
        </ul>
      </div>
    </section>
  );
}
